.TH "wifi-switcher-ru" "1" 
.SH "Название"
.PP
wifi-switcher - автоматический переключатель беспроводных сетей для IceWM и pdmenu.

.SH "Команда"
.PP
wifi-switcher действие [параметры] [модификаторы].br
  действие не начинается с черты, один или несколько параметров начинаются с одной черты, а
один или несколько модификаторов начинаются с двух черт.

.SH "Описание"
.PP
wifi-switcher -- утилита командной строки, предназначенная для автоматического
переключения между беспроводными сетями в соответвии с приоритетом
(присваивается каждой известной сети).

.PP
Программа является надстойкой (оболочкой) над утилитами wpa_\dsupplicant и udhcpc;
предназначена для использования в меню iceWM или в pdmenu;
Для её использования пользователь должен быть участниковм группы netdev.

.PP
Новые (ранее неизвестные) открытые или wpa2-защищённые беспроводные сети могут
быть легко добавлены с помощью динамически появляющегося (в icewm или pdmenu)
меню. Для добавления беспроводных сетей, защищённых иными (не wpa2) протоколами
пользователь должен вручную отредактировать файл
/etc/wpa_\dsupplicant/wifi-switcher.conf в соответствии с инструкциями
`man wpa_\dsupplicant.conf`

.PP
Также программа может быть использована в режиме wifi-сервера.
В этом режима компьютер создаёт собственную беспроводную сеть и запускает
ftp-сервер vsftpd, который может использоваться, например, для обмена файлами с
планшетами и смартфонами.

.SH "Действия (actions)"
.PP
Возможно задание одного из следующих действий: scan, act, connect, и forget.

.PP
scan.br
выводит динамическое меню для каждой из обнаруженных беспроводных сетей.

.PP
act SSID.br
выводит подменю для (первичного или повторного) соединения с выбранной
беспроводной сетью с идентификатором SSID.

.PP
connect SSID.br
соединяется (или пересоединяется) с данной сетью, которая получает наивысший
приоритет; в дальнейшем система по возможности будет пытаться установить
соединение в первую очередь с этой сетью.

.PP
forget SSID.br
забывает данную сеть, так что информация о ней стирается из файла /etc/wpa\dsupplicant/wifi-switcher.conf.br
Забытая сеть становится неизвестной; компьютер не будет подключаться к такой сети автоматически.

.SH "Параметры"
.PP
(взаимоисключающие)

.PP
-icewm.br
для вывода динамического меню в формате IceWM,

.PP
-pdmenu.br
для вывода динамического меню в формате pdmenu.

.SH "Модификаторы"
.PP
--ascii.br
использовать только ascii-символы для отображения амплитуды радиосигнала сети,

.PP
--wifi-hotspot.br
с этим модификатором программа сгенерирует дополнительную строку динамического
меню для перехода в режим wifi-сервера или выхода из него,

.SH "Примеры использования"
.PP
И в оконном менеджере icewm, и в текстовом меню pdmenu wifi-switcher генерирует
динамические меню.
.SS "в меню icewm"
.PP
Типичная строка вызова wifi-switcher в файле ~/.icewm/menu выглядит так:

.PP
menuprogreload wifi - 0 /usr/bin/wifi-switcher -icewm scan --wifi-hotspot

.PP
Эта строка генерирует динамическое меню для каждой из доступных беспроводных сетей.
Имя беспроводной сети, с которой установлено соединение, сопровождается иконкой
/usr/share/wifi-switcher/connected.png
.SS "в pdmenu"
.PP
В файле ~/.pdmenu wifi-switcher может быть вызван следующими командами, действие
которых эквивалентно вышеописанной строке для icewm:

.PP
group:wifi.br
        exec::makemenu:$\ .br
                echo "menu:mainWiFimenu:Choose network:Select the network" ; $\ .br
                /usr/bin/wifi-switcher -pdmenu scan --wifi-hotspot.br
        show:::mainWiFimenu.br
        remove:::mainWiFimenu.br
endgroup

.SH "Файлы конфигурации"
.PP
См. также /usr/share/doc/wifi-switcher/HOTSPOT
.SS "/etc/wpa_\dsupplicant/wifi-switcher.conf"
.PP
Это основной конфигурационный файл, содержащий описание каждой известной беспроводной
сети, включая идентификационные данные (напр., пароли) для закрытых сетей. Если
приходится работать только с открытыми и с простейшими (wpa2) закрытыми сетями, этот
файл необязательно редактировать; за вас это сделает wifi-switcher.

.PP
Ниже показано, как может выглядеть этот файл. Первые две секции были добавлены
программой; третья использует более сложную (enterprise) процедуру шифрования и была
добавлена вручную. Каждая секция содержит приоритет; приоритеты распределяются
программой wifi-switcher автоматически.

.PP
ctrl_\dinterface=/var/run/wpa_\dsupplicant.br

eapol_\dversion=1.br
network={.br
ssid="Hoselton_\dAuto_\dMall".br
key_\dmgmt=WPA-PSK.br
psk=630326a26f999af453239041eec68acdf93788eb7483176001b4fbf17d414a20.br
priority=0.br
}.br
network={.br
ssid="McDonalds Free WiFi".br
key_\dmgmt=NONE.br
priority=9.br
}.br
network={.br
ssid="UR_\dConnected".br
key_\dmgmt=WPA-EAP.br
eap=PEAP.br
identity="myLogin".br
password="myVerySecretPassword".br
phase2="MSCHAPv2".br
priority=33.br
}

.SH "Режим hotspot"
.PP
В этом режиме компьютер создаёт свою собственную (защищённую) беспроводную сеть.
Дополнительно запускается ftp-сервер.
Если подключить к этой сети смартфон, планшет, или ноутбук, можно обмениваться файлами с
этими устройствами по ftp или ssh (если дополнительно установлен ssh-сервер).
Информацию, необходимую для подключения к беспроводной сети а также к ftp серверу,
выдаёт команда
/usr/share/wifi-switcher/hotspot.sh info
которую следует запускать с правами администратора (root).
Параметры подключения можно изменить по команде
dplg-reconfigure wifi-switcher

.SH "Ошибки"
.PP
Об ошибках просьба сообщать Олегу Шалаеву по электронной почте chalaev@gmail.com
Пожалуйста включите в письмо информацию, выдаваемую командой
/usr/share/wifi-switcher/hotspot.sh bugreport
запущеной с административными (root) правами.
.SH "Автор"
.PP
Олег Шалаев <chalaev@gmail.com>.
.SH "Смотреть также"
.PP
\fIhttps://github.com/chalaev/wifi-switcher\fP
