* NAME
  wifi-switcher - Automatic switcher between wifi networks in IceWM and pdmenu.

* SYNOPSIS
  wifi-switcher action [OPTION] [MODIFIER]

* DESCRIPTION
wifi-switcher is a command line utility that automatically switches between
available wireless networks according to priorities set for every known SSID.

wifi-switcher is a wrapper for the wpa__supplicant and udhcpc commands.

The program is designed to be controlled through iceWM menu or pdmenu;
it is restricted to the users from the netdev group.

Newly discovered open and wpa2 SSIDs can easily be configured and added to the
list of known networks.  (For more sophisticated enterprise networks one has to edit\\
/etc/wpa__supplicant/wifi-switcher.conf manually.)  Optionally the wifi
interface can be switched into (ad-hoc) hotspot mode. In this mode, a new (ad-hoc) wifi network is created;
in addition an ftp-server vsftpd is started so that smartphones and other similar devices can exchange files with your linux system.

* ACTIONS
The following actions are available: scan, act, connect, and forget.

scan\\
outputs dynamical menu for each detected wireless network.

act SSID\\
provides submenu for (re)connecting or forgetting the specified SSID.

connect SSID\\
connects to the wireless network with the given SSID. The specified SSID
receives the highest priority, and will be used for connection whenever
possible.

forget SSID\\
forgets this SSID, so that its entry is removed from /etc/wpa_supplicant/wifi-switcher.conf\\
Once the SSID is forgotten, the connection to this network will no longer be automatic.

* OPTIONS
(mutually exclusive)

-icewm\\
output dynamic meny in the IceWM format,

-pdmenu\\
used with pdmenu.

* MODIFIERS
--ascii\\
avoids using unicode symbols to report the wifi signal strength,

--wifi-hotspot\\
with this modifier, the program will generate an extra menu line for switching
into/from the ad-hoc wifi server (hotspot) mode.

--interface=STRING\\
specifies interface, will use wlan0 if not specified.
Names of available network interfaces are available, e.g., in the output of the `ip addr ls` command.

* USAGE
Both in (graphical) icewm, and in (textual) pdmenu wifi-switcher generates dynamic menus:
** in icewm menu
A typical line in the ~/.icewm/menu file:

menuprogreload wifi - 0 /usr/bin/wifi-switcher -icewm scan --wifi-hotspot --interface=wlp2s0b1

This menu line produces dynamic icewm-menu entries with available wifi networks.
If the connection is established the corresponding network is shown on the
second line with the /usr/share/wifi-switcher/connected.png icon.  Protected
networks are marked with the /usr/share/wifi-switcher/locked.png icon.
An optional parameter "--interface" specifies wireless interface (wlan0 by default).
** in pdmenu
A typical entry in the ~/.pdmenu file (similar to the icewm menu entry described above):

group:wifi\\
	exec::makemenu:\ \\
		echo "menu:mainWiFimenu:Choose network:Select the network" ; \ \\
		/usr/bin/wifi-switcher -pdmenu scan --wifi-hotspot\\
	show:::mainWiFimenu\\
	remove:::mainWiFimenu\\
endgroup

* CONFIGURATION FILES
See also /usr/share/doc/wifi-switcher/HOTSPOT
** /etc/wpa__supplicant/wifi-switcher.conf
This file stores priorities and authentification information in the format of a
wpasupplicant configuration file. If only PSK-encrypted and unprotected wireless
networks are available, this file does not need to be edited manually.

Its typical contents is shown below. The first two entries (PSK encryption and
unprotected network) are added by the wifi-switcher; the third one uses more
sophisticated enterprise encryption method and must be set up manually, except
for priority which is adjusted by wifi-switcher.

ctrl__interface=/var/run/wpa__supplicant\\
eapol__version=1\\
network={\\
ssid="Hoselton__Auto__Mall"\\
key__mgmt=WPA-PSK\\
psk=630326a26f999af453239041eec68acdf93788eb7483176001b4fbf17d414a20\\
priority=0\\
}\\
network={\\
ssid="McDonalds Free WiFi"\\
key__mgmt=NONE\\
priority=9\\
}\\
network={\\
ssid="UR__Connected"\\
key__mgmt=WPA-EAP\\
eap=PEAP\\
identity="myLogin"\\
password="myVerySecretPassword"\\
phase2="MSCHAPv2"\\
priority=33\\
}

* HOTSPOT MODE
In this mode, a separate wifi-network is created and ftp server is activated.
This is particularly useful for downloading/uploading files to/from smartphones and
tablets. To see the corresponding settings (e.g., passwords) run
/usr/share/wifi-switcher/hotspot.sh info
with root priviledges. To change the settings, run dplg-reconfigure wifi-switcher.

* BUGS
  Email bug reports to Oleg Shalaev <chalaev@gmail.com>
  Please include output of the command
  /usr/share/wifi-switcher/hotspot.sh bugreport

* AUTHOR
  Written by Oleg Shalaev <chalaev@gmail.com>.
* SEE ALSO
  https://github.com/chalaev/wifi-switcher


