* Название
  wifi-switcher - автоматический переключатель беспроводных сетей для IceWM и pdmenu.

* Команда
  wifi-switcher действие [параметры] [модификаторы]\\
  действие не начинается с черты, один или несколько параметров начинаются с одной черты, а
  один или несколько модификаторов начинаются с двух черт.

* Описание
wifi-switcher -- утилита командной строки, предназначенная для автоматического
переключения между беспроводными сетями в соответвии с приоритетом
(присваивается каждой известной сети).

Программа предназначена для использования в меню IceWM или в pdmenu;
Для её использования пользователь должен быть участниковм группы netdev.

wifi-switcher представляет собой надстройку (оболочку) над утилитами
wpa__supplicant, udhcpc, hostapd и isc-dhcp-server.
Она конфигурирует их, предполагая, что никто другой ими не пользуется.
По умолчанию hostapd и isc-dhcp-server автоматически запускаются во время загрузки компьютера, и это мешает работе
wifi-switcher.
Отключить авто-загрузку можно, запустив следующую команду (с правами root):
#+BEGIN_SRC sh
for i in $(service --status-all | grep "hostapd\\|isc-dhcp-server" | awk '{print $NF}') ; do
    update-rc.d -f $i remove
done
#+END_SRC
(Возможно, вы захотите отключить аналогичным образом также и vsftpd.)
Можно и не отключать авто-загрузку, но тогда следует добавить строку
#+BEGIN_SRC sh
sudo /usr/sbin/service hostapd stop
#+END_SRC
в пользовательский файл ~/.profile

Новые (ранее неизвестные) открытые или wpa2-защищённые беспроводные сети могут
быть легко добавлены с помощью динамически появляющегося (в icewm или pdmenu)
меню. Для добавления беспроводных сетей, защищённых иными (не wpa2) протоколами
пользователь должен вручную отредактировать файл
/etc/wpa__supplicant/wifi-switcher.conf в соответствии с инструкциями
(см. man wpa__supplicant.conf)

Также программа может быть использована в режиме wifi-сервера.
В этом режима компьютер создаёт собственную беспроводную сеть и запускает
ftp-сервер vsftpd, который может использоваться, например, для обмена файлами с
планшетами и смартфонами.

* Действия (actions)
Возможно задание одного из следующих действий: scan, act, connect, и forget.

scan\\
выводит динамическое меню для каждой из обнаруженных беспроводных сетей.

act SSID\\
выводит подменю для (первичного или повторного) соединения с выбранной
беспроводной сетью с идентификатором SSID.

connect SSID\\
соединяется (или пересоединяется) с данной сетью, которая получает наивысший
приоритет; в дальнейшем система по возможности будет пытаться установить
соединение в первую очередь с этой сетью.

forget SSID\\
забывает данную сеть, так что информация о ней стирается из файла /etc/wpa_supplicant/wifi-switcher.conf\\
Забытая сеть становится неизвестной; компьютер не будет подключаться к такой сети автоматически.

* Параметры
(взаимоисключающие)

-icewm\\
для вывода динамического меню в формате IceWM.

-pdmenu\\
для вывода динамического меню в формате pdmenu.

* Модификаторы
--ascii\\
использовать только ascii-символы для отображения амплитуды радиосигнала сети.

--wifi-hotspot\\
с этим модификатором программа сгенерирует дополнительную строку динамического
меню для перехода в режим wifi-сервера или выхода из него.

* Примеры использования
И в оконном менеджере icewm, и в текстовом меню pdmenu wifi-switcher генерирует
динамические меню.
** в меню icewm
Типичная строка вызова wifi-switcher в файле ~/.icewm/menu выглядит так:

menuprogreload wifi - 0 /usr/bin/wifi-switcher -icewm scan --wifi-hotspot

Эта строка генерирует динамическое меню для каждой из доступных беспроводных сетей.
Имя беспроводной сети, с которой установлено соединение, сопровождается иконкой
/usr/share/wifi-switcher/connected.png
** в pdmenu
В файле ~/.pdmenu wifi-switcher может быть вызван следующими командами, действие
которых эквивалентно вышеописанной строке для icewm:

#+BEGIN_SRC conf
group:wifi
	exec::makemenu:\\
		echo "menu:mainWiFimenu:Choose network:Select the network" ; \\
		/usr/bin/wifi-switcher -pdmenu scan --wifi-hotspot
	show:::mainWiFimenu
	remove:::mainWiFimenu
endgroup
#+END_SRC

* Файлы конфигурации
См. также /usr/share/doc/wifi-switcher/HOTSPOT
** /etc/wpa__supplicant/wifi-switcher.conf
Это основной конфигурационный файл, содержащий описание каждой известной беспроводной
сети, включая идентификационные данные (напр., пароли) для закрытых сетей. Если
приходится работать только с открытыми и с простейшими (wpa2) закрытыми сетями, этот
файл необязательно редактировать; за вас это сделает wifi-switcher.

Ниже показано, как может выглядеть этот файл. Первые две секции были добавлены
программой; третья использует более сложную (enterprise) процедуру шифрования и была
добавлена вручную. Каждая секция содержит приоритет; приоритеты распределяются
программой wifi-switcher автоматически.

#+BEGIN_SRC conf
ctrl_interface=/var/run/wpa_supplicant
eapol_version=1
network={
ssid="Hoselton_Auto_Mall"
key_mgmt=WPA-PSK
psk=630326a26f999af453239041eec68acdf93788eb7483176001b4fbf17d414a20
priority=0
}
network={
ssid="McDonalds Free WiFi"
key_mgmt=NONE
priority=9
}
network={
ssid="UR_Connected"
key_mgmt=WPA-EAP
eap=PEAP
identity="myLogin"
password="myVerySecretPassword"
phase2="MSCHAPv2"
priority=33
}
#+END_SRC

* Режим hotspot
В этом режиме компьютер создаёт свою собственную (защищённую) беспроводную сеть.
Дополнительно запускается ftp-сервер.
Если подключить к этой сети смартфон, планшет, или ноутбук, можно обмениваться файлами с
этими устройствами по ftp или ssh (если дополнительно установлен ssh-сервер).
Информацию, необходимую для подключения к беспроводной сети а также к ftp серверу,
выдаёт команда
/usr/share/wifi-switcher/hotspot.sh info
которую следует запускать с правами администратора (root).
Параметры подключения можно изменить по команде
dplg-reconfigure wifi-switcher

* Ошибки
  Об ошибках просьба сообщать Олегу Шалаеву по электронной почте chalaev@gmail.com
  Лучше всего воспользоваться для этого командой
  #+BEGIN_SRC sh
  reportbug --no-debconf wifi-switcher
  #+END_SRC
  Внимание: перед тем, как письмо с сообщением об ошибке будет отправлено, удалите в конце его секцию
  #+BEGIN_SRC conf
 -- Configuration Files:
  #+END_SRC
  которая может содержать ваши пароли для беспроводных сетей. (Пожалуйста, не используйте опции --no-config-files или -c программы
  reportbug; они уберут из сообщения не только секцию "Configuration Files", но и другую важную информацию.)
* Автор
  Олег Шалаев <chalaev@gmail.com>.
* Смотреть также
  https://github.com/chalaev/wifi-switcher\\
  http://chalaev.com/wifi-switcher

