* Название
  wifi-switcher - автоматический переключатель беспроводных сетей для IceWM и pdmenu.

* Команда
  wifi-switcher действие [параметры] [модификаторы]\\
  действие не начинается с черты, один или несколько параметров начинаются с одной черты, а
  один или несколько модификаторов начинаются с двух черт.

* Описание
wifi-switcher -- утилита командной строки, предназначенная для автоматического
переключения между беспроводными сетями в соответвии с приоритетом
(присваивается каждой известной сети).

Программа является надстойкой (оболочкой) над утилитами wpa__supplicant и udhcpc;
предназначена для использования в меню iceWM или в pdmenu;
Для её использования пользователь должен быть участниковм группы netdev.

Новые (ранее неизвестные) открытые или wpa2-защищённые беспроводные сети могут
быть легко добавлены с помощью динамически появляющегося (в icewm или pdmenu)
меню. Для добавления беспроводных сетей, защищённых иными (не wpa2) протоколами
пользователь должен вручную отредактировать файл
/etc/wpa__supplicant/wifi-switcher.conf в соответствии с инструкциями
`man wpa__supplicant.conf`

Также программа может быть использована в режиме wifi-сервера.
В этом режима компьютер создаёт собственную беспроводную сеть и запускает
ftp-сервер vsftpd, который может использоваться, например, для обмена файлами с
планшетами и смартфонами.

* Действия (actions)
Возможно задание одного из следующих действий: scan, act, connect, и forget.

scan\\
выводит динамическое меню для каждой из обнаруженных беспроводных сетей.

act SSID\\
выводит подменю для (первичного или повторного) соединения с выбранной
беспроводной сетью с идентификатором SSID.

connect SSID\\
соединяется (или пересоединяется) с данной сетью, которая получает наивысший
приоритет; в дальнейшем система по возможности будет пытаться установить
соединение в первую очередь с этой сетью.

forget SSID\\
забывает данную сеть, так что информация о ней стирается из файла /etc/wpa_supplicant/wifi-switcher.conf\\
Забытая сеть становится неизвестной; компьютер не будет подключаться к такой сети автоматически.

* Параметры
(взаимоисключающие)

-icewm\\
для вывода динамического меню в формате IceWM,

-pdmenu\\
для вывода динамического меню в формате pdmenu.

* Модификаторы
--ascii\\
использовать только ascii-символы для отображения амплитуды радиосигнала сети,

--wifi-hotspot\\
с этим модификатором программа сгенерирует дополнительную строку динамического
меню для перехода в режим wifi-сервера или выхода из него,

--interface=СТРОКА\\
задаёт интерфейс беспроводной сети, wlan0 по умолчанию.
Имена доступных сетевых интерфейсов можно узнать, например, воспользовавшись командой `ip addr ls`

* Примеры использования
И в оконном менеджере icewm, и в текстовом меню pdmenu wifi-switcher генерирует
динамические меню.
** в меню icewm
Типичная строка вызова wifi-switcher в файле ~/.icewm/menu выглядит так:

menuprogreload wifi - 0 /usr/bin/wifi-switcher -icewm scan --wifi-hotspot --interface=wlp2s0b1

Эта строка генерирует динамическое меню для каждой из доступных беспроводных сетей.
Имя беспроводной сети, с которой установлено соединение, сопровождается иконкой
/usr/share/wifi-switcher/connected.png
Необязательный параметр "--interface" указывает имя интерфейса беспроводной сети (по умолчанию wlan0).
** в pdmenu
В файле ~/.pdmenu wifi-switcher может быть вызван следующими командами, действие
которых эквивалентно вышеописанной строке для icewm:

group:wifi\\
	exec::makemenu:\ \\
		echo "menu:mainWiFimenu:Choose network:Select the network" ; \ \\
		/usr/bin/wifi-switcher -pdmenu scan --wifi-hotspot --interface=wlp2s0b1\\
	show:::mainWiFimenu\\
	remove:::mainWiFimenu\\
endgroup

* Файлы конфигурации
См. также /usr/share/doc/wifi-switcher/HOTSPOT
** /etc/wpa__supplicant/wifi-switcher.conf
Это основной конфигурационный файл, содержащий описание каждой известной беспроводной
сети, включая идентификационные данные (напр., пароли) для закрытых сетей. Если
приходится работать только с открытыми и с простейшими (wpa2) закрытыми сетями, этот
файл необязательно редактировать; за вас это сделает wifi-switcher.

Ниже показано, как может выглядеть этот файл. Первые две секции были добавлены
программой; третья использует более сложную (enterprise) процедуру шифрования и была
добавлена вручную. Каждая секция содержит приоритет; приоритеты распределяются
программой wifi-switcher автоматически.

ctrl__interface=/var/run/wpa__supplicant\\
eapol__version=1\\
network={\\
ssid="Hoselton__Auto__Mall"\\
key__mgmt=WPA-PSK\\
psk=630326a26f999af453239041eec68acdf93788eb7483176001b4fbf17d414a20\\
priority=0\\
}\\
network={\\
ssid="McDonalds Free WiFi"\\
key__mgmt=NONE\\
priority=9\\
}\\
network={\\
ssid="UR__Connected"\\
key__mgmt=WPA-EAP\\
eap=PEAP\\
identity="myLogin"\\
password="myVerySecretPassword"\\
phase2="MSCHAPv2"\\
priority=33\\
}

* Режим hotspot
В этом режиме компьютер создаёт свою собственную (защищённую) беспроводную сеть.
Дополнительно запускается ftp-сервер.
Если подключить к этой сети смартфон, планшет, или ноутбук, можно обмениваться файлами с
этими устройствами по ftp или ssh (если дополнительно установлен ssh-сервер).
Информацию, необходимую для подключения к беспроводной сети а также к ftp серверу,
выдаёт команда
/usr/share/wifi-switcher/hotspot.sh info
которую следует запускать с правами администратора (root).
Параметры подключения можно изменить по команде
dplg-reconfigure wifi-switcher

* Ошибки
  Об ошибках просьба сообщать Олегу Шалаеву по электронной почте chalaev@gmail.com
  Пожалуйста включите в письмо информацию, выдаваемую командой
  /usr/share/wifi-switcher/hotspot.sh bugreport
  запущеной с административными (root) правами.
* Автор
  Олег Шалаев <chalaev@gmail.com>.
* Смотреть также
  https://github.com/chalaev/wifi-switcher


