#!/bin/sh -e

case "$1" in
    purge)

	for i in $(service --status-all | grep "hostapd\|vsftpd\|x11-common" | awk '{print $NF}') ; do
	    echo "restoring default service for $i"
	    update-rc.d -f $i defaults
	done

	for i in /etc/wpa_supplicant/wifi-switcher.conf /etc/vsftpd-wifi.db \
/etc/sudoers.d/wifi-switcher /etc/network/interfaces.d/wifi-switcher \
/etc/dhcp/wifi-switcher.conf /etc/hostapd/wifi-switcher.conf \
/etc/default/isc-dhcp-server.wifi  /etc/default/wifi-switcher \
/etc/wpa_supplicant/wifi-switcher.conf ; do
	    if [ -e $i ]; then
		rm $i
	    fi
	done

	#  rm /var/log/wifi-switcher

        # if [ -x "$(command -v deluser)" ]; then
        #     deluser --quiet --system wsftp > /dev/null || true
        # else
        #     echo >&2 "not removing wsftp system account because deluser command was not found"
        # fi

	# echo  >&2 "wifi-switcher: remove the ftp user manually if you do not need it any more"
	exit 0
	# -- without this "exit 0", update-rc.d leads to exit code 128
	;;

    remove|upgrade|faild-upgrade|abort-*|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
esac

#DEBHELPER#

exit 0
